version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "33062:3306"
  web:
    build:
      context: "./"
      dockerfile: docker-dev/web.Dockerfile
    volumes_from:
      - app
    ports:
      - "8089:80"
  app:
    build:
      context: "./"
      dockerfile: docker-dev/app.Dockerfile
    volumes:
      - ./:/var/www/app
    environment:
      - TEST=2
